protobuf-c/protobuf-c

t/generated-code2/test-generated-code2.c
```
t/generated-code2/test-generated-code2.c:2005:25: warning: assigning to 'uint8_t *' (aka 'unsigned char *') from 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
m.required_bytes.data = str; m.required_bytes.len = 1;
^ ~~~
t/generated-code2/test-generated-code2.c:2019:25: warning: assigning to 'uint8_t *' (aka 'unsigned char *') from 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
m.required_bytes.data = str; m.required_bytes.len = 1;
^ ~~~
t/generated-code2/test-generated-code2.c:2044:25: warning: assigning to 'uint8_t *' (aka 'unsigned char *') from 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
m.optional_bytes.data = str; m.optional_bytes.len = 1;
^ ~~~ …
```
=> Fix compile warnings about pointers of different types assignments

protoc-c/c_helpers.cc
Certain protobuf comments could generate invalid C comments
and inadvertently close the comment block. This commit removes '/'
signs in such comments
=> protoc-c/c_helpers.cc: Enhance comment string parsing

Makefile.am, protobuf-c/protobuf-c.c, protobuf-c/protobuf-c.h, protoc-c/c_enum.cc, protoc-c/c_field.cc, protoc-c/c_message.cc, protoc-c/c_service.cc, t/generated-code2/test-generated-code2.c, t/test-optimized.proto
Adds support for the `LITE_RUNTIME` optimization option to the protobuf-c
compiler. Enabling this option would generate lighter weight message,
enum, and service descriptors that contain NO strings. As a result,
calls to lookup descriptors via the `*_get_{field,value,method}_by_name`
API will return `NULL`.
Default compiler behavior (when optimize_for is not specified or is not
set to `LITE_RUNTIME`) is unchanged.
This option is useful for various reasons:
1. Projects with a large number of structures and enums defined using .proto files will see a significant code size reduction when using the `LITE_RUNTIME` option with protobuf-c since descriptors will take up less space.
2. For security reasons when the exposure of enum or message names in the object code is not desirable.
One con is …
=> Lite runtime

protobuf-c/protobuf-c.c
```
make protobuf-c/libprotobuf-c.la CFLAGS="-Wsign-compare"
```
This produces several warnings like these:
```
warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```
=> Fix -Wsign-compare warnings

protobuf-c/protobuf-c.c
```
make protobuf-c/libprotobuf-c.la CFLAGS="-Wdeclaration-after-statement"
```
produces several warnings like:
```
warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
```
This switch is default for C89 standard, so these warnings are problematic when embedding protobuf-c library into C89-compliant project.
=> Fix ISO C90 -Wdeclaration-after-statement warnings

protobuf-c/protobuf-c.c
It was partly fixed by 1f5e813.
=> Fix bigendian -Wunused-label warning

Makefile.am
remove .pb.{cc,h} in distdir instead of top_distdir in order to
prevent removing files from other projects when protobuf-c is
included as an autotools subproject.
=> protobuf-c: fix: make dist

configure.ac
Hello,
I'm part of a team working on a project that (I believe) would benefit greatly from protobuf-c. Part of our constraints are that we have to work on scientific linux 6, sadly, which is rather old:
* _uname_ outputs 2.6.32-642.1.1.el6.x86_64)
* _autom4te --version_ outputs autom4te (GNU Autoconf) 2.6**3**
My initial attempt to build the master protobuf-c branch failed - it reported that the autom4te version was too old (2.64 required, 2.63 found). I relaxed the constraint to 2.63 and protobuf-c builds fine on the target environment.
Would it be possible to relax the constraint from 2.64 -> 2.63 ?
=> relax constraint from v2.64 -> v2.63 (so that it works on SL6)

Makefile.am
Building on solaris fails since the `rm` command (at least on solaris 10) does not know the `-v` argument. This patch removes the argument.
=> rm argument fix for solaris

protoc-c/c_message.cc
Making `init_value` `const` will (with typical compilers) remove the need to reserve space for a copy in the bss section since the value can not change and can directly be copied from the data section (where it is needed anyway).
This reduces the amount of needed memory by one message size (which might be relevant if there are a lot of different messages or there are large messages).
=> make init_value const

protobuf-c/protobuf-c.h, protoc-c/c_message.cc, t/generated-code2/test-generated-code2.c
For protobuf_c_message_free_unpacked() this just documents the existing behavior.
For the generated functions this causes them to do nothing when a null message pointer is supplied, aligning them with the behavior of free() and thus simplifying callers.
=> Document and extend the effect of passing NULL to ..._free_unpacked functions

.travis.yml, Makefile.am, configure.ac, protobuf-c/protobuf-c.c, protobuf-c/protobuf-c.h, protoc-c/c_bytes_field.cc, protoc-c/c_enum_field.cc, protoc-c/c_field.cc, protoc-c/c_helpers.h, protoc-c/c_primitive_field.cc, t/test-proto3.proto
This is an experimental first cut at adding proto3 support and I have not
tested it further than porting to proto3 the testcase. Before pushing
this further I would like to have some feedback on whether I am on
the right track.
As far as I understand protobuf-c already has pretty much everything
needed once it is built using a new version of protibuf itself.
The only missing thing is that in proto3 all fields are optional and
having to manually set has_foo is inconvenient.
This patch special cases the proto3 syntax files so that structs for the
bytes, enum and primitive fields do not emit the has_ field.
It also adds PROTOBUF_C_LABEL_NONE to the label enum that is used for
proto3 fields. When a fields has this label, the quantifier is not
consulted and instead the field is packed/unpacked …
=> proto3 support

build-cmake/CMakeLists.txt
I have to build protobuf-c for Windows using VS2015. I have to use static libraries so that MSVCR*.DLL is not required at runtime.
This is achieved by replacing MSVS option /MD with /MT and /MDd with /MTd
[http://www.cmake.org/Wiki/CMake_FAQ#How_can_I_build_my_MSVC_application_with_a_static_runtime.3F]
The same solution is already implemented in google protobuf [https://github.com/google/protobuf/blob/master/cmake/CMakeLists.txt]
=> Static build for Windows MSVC

configure.ac, m4/ax_check_compile_flag.m4, protobuf-c/protobuf-c.c
It turns out we weren't compiling with ***any*** warning flags at all.
Fix a shadowed variable in `protobuf_c_message_unpack()`, found with `-Wshadow`.
=> Add warning flags to my_CFLAGS

protobuf-c/protobuf-c.c
Small fixup for https://github.com/protobuf-c/protobuf-c/pull/228
I had that FIXME because I was not 100% sure if in proto3 sub messages that are sent more than once should me merged or if they are invalid... Let's assume they are exactly the same as proto2 optional messages and remove the FIXME
=> Remove leftover FIXME comment

Makefile.am, protobuf-c/protobuf-c.c, t/generated-code/test-generated-code.c, t/test-proto3.proto, t/test.proto
This is probably the cause of issue #262 and most importantly it avoids accessing uninitialized mem as reported by valgrind.
Improvements to the unit tests are included (the unit test was passing but valgrind catches the problem)
=> Fix proto3 "is zeroish" evaluation

protobuf-c/protobuf-c.c
The "member" param cannot be NULL, so last patch was not correct.
However to be valgrind clean we need to cast to the right size.
=> Rework is_zeroish one more time

protobuf-c/libprotobuf-c.sym, protobuf-c/protobuf-c.c, protobuf-c/protobuf-c.h, protoc-c/c_field.cc, protoc-c/c_string_field.cc, t/generated-code/test-generated-code.c
The spec talks about "empty string" and other languages like C#
return a zero length string and not null.
This is useful because when moving from proto2's "required string"
to a proto3's plain string we will be guaranteed that we
never get a null pointer.
The tradeoff is adding a special case to the library but avoiding
a lot of null checks in the calling code.
The current code is already special casing "" in pack_string.
=> proto3: make strings default to "" instead of NULL

protoc-c/c_bytes_field.cc, protoc-c/c_bytes_field.h, protoc-c/c_enum.cc, protoc-c/c_enum_field.cc, protoc-c/c_enum_field.h, protoc-c/c_field.cc, protoc-c/c_helpers.cc, protoc-c/c_message.cc, protoc-c/c_message_field.cc, protoc-c/c_primitive_field.cc, protoc-c/c_service.h, protoc-c/c_string_field.cc, protoc-c/c_string_field.h
The protobuf project removed "using namespace std" namespace pollution
from their stubs/common.h header file. This caused build failures for us
since we relied on their namespace pollution.
This commit updates protobuf-c to convert:
'map' → 'std::map'
'set' → 'std::set'
'back_insert_iterator' → 'std::back_insert_iterator'
=> Fix namespace errors when compiled with latest protobuf

protoc-c/c_file.cc
The changes in #274 (proto3: make strings default to "" instead of NULL) add a new symbol to the library and add an `extern` declaration to the protobuf-c header file.
Since the compiler may generate files that depend on that new `protobuf_c_empty_string` declaration in protobuf-c.h, we need to bump the `min_header_version` value that is written into generated header files. But since the `protobuf_c_empty_string` symbol can only be referenced when generating proto3 syntax files, we only need to use the stricter `min_header_version` value when processing a proto3 file.
=> Bump minimum required header version for proto3 syntax

protoc-c/c_file.cc
The change in commit 712154b912de824741381c0bb26c2fbed54515a3 ("Bump minimum required header version for proto3 syntax") uses functionality only exposed by protobuf-3.x, breaking the build when compiling against protobuf-2.x.
Since we still want to support building against protobuf-2.x, this commit makes the proto3 syntax check in the file generator dependent on building against protobuf-3.x.
=> Restore protobuf-2.x compatibility

.travis.yml
This branch updates Travis to use the xenial base image rather than trusty, and installs the latest protobuf 3.6.1 release. Note that we need to set the environment variable `CXX="g++ -std=c++11"` due to xenial using an older g++ version.
The CI build is not currently successful because we also need some additional fixes due to changes in protobuf.
=> Update Travis to use xenial, protobuf 3.6.1

protoc-c/c_field.cc, protoc-c/c_field.h, protoc-c/c_file.cc, protoc-c/c_file.h, protoc-c/c_generator.cc, protoc-c/c_helpers.cc, protoc-c/c_message.cc, protoc-c/c_message.h
Upstream protobuf removed scoped_ptr.h, which provided the `scoped_ptr` that we depended on, in commit https://github.com/google/protobuf/commit/67952fab2c766ac5eacc15bb78e5af4039a3d398.
This commit converts uses of `scoped_ptr` type to idiomatic C++11 `std::unique_ptr`, similar to the changes in the protobuf commit.
This has been tested on protobuf 3.0.0 (the version currently in Debian) as well as the latest protobuf 3.6.1 release.
=> Convert uses of protobuf's scoped_ptr.h to C++11 std::unique_ptr

protobuf-c/protobuf-c.c
Check the return value of int_range_lookup before using as an array index; it can return -1
=> Check the return value of int_range_lookup

.travis.yml, configure.ac, m4/ax_cxx_compile_stdcxx.m4
This branch adds the `AX_CXX_COMPILE_STDCXX` macro from the autoconf-archive and uses it when the protobuf-c compiler is being built. This is needed on C++ compilers that are new enough to support C++11 but old enough to not enable support for C++11 features by default.
=> Use AX_CXX_COMPILE_STDCXX macro to enable C++11 support in old compilers

.travis.yml
This bumps the protobuf version built in Travis-CI to 3.7.1, which replicates the build failure in the test suite.
=> .travis.yml: Bump protobuf version to 3.7.1, use new URL

t/generated-code2/cxx-generate-packed-data.cc
`google::protobuf::Message::Reflection` has been removed in newer versions
of protobuf. The replacement is `google::protobuf::Reflection`.
protobuf in commit protocolbuffers/protobuf@779f61c6a3ce02a119e28e802f229e61b69b9046 ("Integrate recent changes from google3.", from August 2008) changed the following in message.h:
```diff
@@ -336,7 +337,8 @@ class LIBPROTOBUF_EXPORT Message {
// Introspection ---------------------------------------------------
-  class Reflection;  // Defined below.
+  // Typedef for backwards-compatibility.
+  typedef google::protobuf::Reflection Reflection;
```
The "typedef for backwards-compatibility" apparently lasted ten years until protobuf commit protocolbuffers/protobuf@6bbe197e9c1b6fc38cbdc45e3bf83fa7ced792a3 ("Down-integrate from google3.", from August …
=> t/generated-code2/cxx-generate-packed-data.cc: Fix build failure on newer protobuf

protobuf-c/protobuf-c.c, t/generated-code2/test-generated-code2.c
The `protobuf_c_message_check` function used to dereference unpopulated 'oneof' members that are messages, while scalar members were populated. This would cause segfaults or other errors.
Example .proto file to reproduce the problem:
```
syntax = "proto2";
package testing;
message TestMessage {
message SubMessage {
required string sub_a = 1;
required string sub_b = 2;
}
oneof Type {
string oneof_a = 1;
string oneof_b = 2;
SubMessage sub = 3;
}
}
```
example code to reproduce the crash:
```
#include "generated_code/main.idl.pb-c.h"
int main()
{
Testing__TestMessage msg = TESTING__TEST_MESSAGE__INIT;
msg.type_case = TESTING__TEST_MESSAGE__TYPE_ONEOF_A;
msg.oneof_a = "Hello, world!";
protobuf_c_message_check((ProtobufCMessage *)&msg);
return 0;
}
```
Signed-off-by: Hayri Ugur Koltuk …
=> Fix a SEGV on on protobuf_c_message_check on messages with 'oneof's inside

protobuf-c/protobuf-c.c
This is needed because in the syntax of Google protobuf the zero
value is not valid tag value. The specification
(https://developers.google.com/protocol-buffers/docs/proto3) says
that "The smallest tag number you can specify is 1, and the largest
is 2^29-1, or 536,870,911."
=> Check if tag is equal to 0

Makefile.am
Issue #330 is a bug in proto3 behavior and the test case handling it needs a `syntax = "proto3";` line in its .proto file, which is not supported by the protobuf 2 implementation.
Since we still support building against protobuf 2, this commit conditionalizes the Issue #330 test case so that it is only built when protobuf-c is being built against protobuf 3.
=> Makefile.am: Only enable the Issue #330 test case when building against protobuf 3.x

.travis.yml
Code coverage option was removed in the xenial update change (fe36c1677)
=> .travis.yml: Reenable code coverage

t/generated-code2/test-generated-code2.c
I fixed a couple test assertions here that seemed to be accidentally
using assignment (=) instead of equality (==).
=> Fixed some test assertions in test-generated-code2.c

protobuf-c/protobuf-c.c
Also match upstream code in src/google/protobuf/wire_format_lite.h
See https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wire_format_lite.h
=> protobuf-c.c: Make zigzag encoding more compact

protobuf-c/protobuf-c.h
protobuf_c_empty_string is used in generated .pb-c.{c,h} files so it
should be exported properly. Fixes #331
=> protobuf-c.h: Fix Windows DLL export (Fixes #331)

protobuf-c/protobuf-c.c
Resolves an ambiguity that %zu was meant to address, since %zu is not
present on all platforms.
Fixes #357.
=> protobuf-c.c: Cast %lu args to unsigned long int

protobuf-c/protobuf-c.c, protoc-c/c_message.cc, protoc-c/c_service.cc
Fixes #188.
Implements suggested fix from the issue:
The struct tag namespace is different from the type namespace. Use the
same symbol names (i.e. without leading underscores) in every namespace.
=> protoc-c: Remove leading underscores from structs

.travis.yml
Travis CI supports arm64, s390x and ppc64le now. It would be nice to test on those platforms, you get all sorts of interesting quirks (s390x is big-endian, for example).
If any issues come up with the ppc64le build in future, feel free to tag me in and I'll have a look - I have access to ppc64le systems at work. I can also help find a s390x person if that goes wrong there.
This involves bumping the Travis environment to Bionic, I don't think that will cause any dramas, it just gives us access to more recent compilers.
=> Travis CI: Test on other platforms

protoc-c/c_bytes_field.cc, protoc-c/c_bytes_field.h, protoc-c/c_enum.cc, protoc-c/c_enum.h, protoc-c/c_enum_field.cc, protoc-c/c_enum_field.h, protoc-c/c_extension.cc, protoc-c/c_extension.h, protoc-c/c_field.cc, protoc-c/c_field.h, protoc-c/c_file.cc, protoc-c/c_file.h, protoc-c/c_generator.cc, protoc-c/c_generator.h, protoc-c/c_helpers.cc, protoc-c/c_helpers.h, protoc-c/c_message.cc, protoc-c/c_message.h, protoc-c/c_message_field.cc, protoc-c/c_message_field.h, protoc-c/c_primitive_field.cc, protoc-c/c_primitive_field.h, protoc-c/c_service.cc, protoc-c/c_service.h, protoc-c/c_string_field.cc, protoc-c/c_string_field.h
The protobuf common.h header currently has a "using std::string;"
statement that pulls std::string into the google::protobuf namespace:
https://github.com/protocolbuffers/protobuf/blob/ce66f6047db44df3234bccd6fcf468bccc14a760/src/google/protobuf/stubs/common.h#L195
I plan to delete that line soon. To keep protobuf-c working, this commit
updates the generator to fully qualify std::string.
=> Updated the generator to fully qualify std::string

build-cmake/CMakeLists.txt
A user of the protobuf-c library is confronted with MSVC warnings about missing
PDB if the library happens to be built/configured using the CMAKE_BUILD_TYPE
"Debug" or "RelWithDebInfo". This commit deals away with the warning by
installing the "protobuf-c.pdb" alongside the lib. The .pdb is installed only
if it exists. Configuring "Release" or building under Linux won't produce and
won't install the PDB.
=> Install debug symbols alongside the protobuf-c.lib

protobuf-c/protobuf-c.c
Use `_attribute__((__unused__))` for the `allocator_data` parameter of functions `system_alloc` and `system_free`. This allows us to integrate the file into build environments in which the "unused function parameter" warning is active. For example, with gcc 10 this avoids the following warnings:
```
protobuf-c.c: In function ‘system_alloc’:
protobuf-c.c:149:44: error: unused parameter ‘allocator_data’ [-Werror=unused-parameter]
149 | system_alloc(void *__attribute__((unused)) allocator_data, size_t size)
|              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
protobuf-c.c: In function ‘system_free’:
protobuf-c.c:155:43: error: unused parameter ‘allocator_data’ [-Werror=unused-parameter]
155 | system_free(void *__attribute__((unused)) allocator_data, void *data)
| …
```
=> Avoid "unused function parameter" compiler warning

protobuf-c/protobuf-c.c
protobuf-c parsing code operates on wire type as uint8_t, so keep it
defined as such to avoid confusion and unnecessary compiler warnings.
Supersedes #379
=> protobuf-c: don't use ProtobufCWireType internally

.github/workflows/build.yml
The push trigger didn't seem to work for PRs based in outside repos. So limit the push trigger to master and next and enable a PR trigger.
=> Run GitHub actions also on pull requests

protobuf-c/protobuf-c.c
This converts the arithmetic shifts to logical shifts and fixes issue #506.
It is based in part on a stackoverflow answer by John Schultz,
https://stackoverflow.com/questions/4533076/google-protocol-buffers-zigzag-encoding
=> Only shift unsigned values to avoid implementation-specific behavior.

Makefile.am
protoc depends on protobuf libraries for execution. Order libraries
accordingly. Observing link errors with yocto's meta-mingw project
during static linkage.
Signed-off-by: Sinan Kaya <sinan.kaya@microsoft.com>
=> Makefile.am: change link order

.github/workflows/build.yml
Windows builds fail on GitHub due to missing unzip:
https://github.com/protobuf-c/protobuf-c/actions/runs/3120315250/jobs/5060804075
7zip is [installed on the GitHub runners](https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md#tools) and can be used instead.
=> GitHub actions fail on Windows due to missing unzip command

build-cmake/.gitignore, build-cmake/CMakeLists.txt, build-cmake/Config.cmake.in
The steps to add this functionality are from the cmake tutorial:
https://cmake.org/cmake/help/latest/guide/tutorial/index.html
The include directories being set on the targets is necessary
for dependent targets. There is some redundancy with the
INCLUDE_DIRECTORIES calls alreday present, but I left it alone
to make the PR smaller and more approachable.
The project currently uses mixed cases in functions. This uses
lowercase on calls I touched, as this is what CMake documentation
uses and seems to be the preferred way.
I also started wrapping long lines, as some of the lines I touched
were over 170 characters.
I tested this on both Mac OS 10.15 Catalina and CentOS 7 (with
devtoolset-7) with CMake 3.10.3.
=> Export and install CMake targets

build-cmake/CMakeLists.txt
It is much better to use CMAKE_CURRENT_BINARY_DIR instead of CMAKE_BINARY_DIR, because it improves compatibility. With CMAKE_BINARY_DIR the building will fail for the project included in another CMake project using add_subdirectory. It makes harder usage of protobuf-c without requirement of installation it on the build system.
Details: https://github.com/protobuf-c/protobuf-c/issues/480
=> Use CMAKE_CURRENT_BINARY_DIR instead of CMAKE_BINARY_DIR

protobuf-c/protobuf-c.c
```
clang --version
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: x86_64-apple-darwin21.6.0
cd protobuf-c && clang -Wall -DNDEBUG -c protobuf-c.c -o protobuf.o
protobuf-c.c:1921:10: warning: variable 'tmp' set but not used [-Wunused-but-set-variable]
size_t tmp;
^
1 warning generated.
```
I based my change off of the commit in #453 to try to match the style of the repo, but a `#ifdef NDEBUG` could be used instead.
=> Avoid "unused variable" compiler warning

configure.ac, t/generated-code2/test-generated-code2.c
Turn off some compiler diagnostics that clutter the build output and aren't particularly useful.
=> Silence some compiler diagnostics

build-cmake/CMakeLists.txt
Otherwise cmake won't reconize the command.
With double hyphens:
```
$ cmake -E env TESTENV=value -- env | grep TESTENV
cmake -E env: unknown option '--'
```
Without double hyphens:
```
$ cmake -E env TESTENV=value env | grep TESTENV
TESTENV=value
```
=> CMakeList.txt: Remove double hyphens

README.md
The canonical doman is no longer dot-io, though both work.
=> Update link to Autotools Mythbuster.

protobuf-c/protobuf-c.c
A memory corruption in protobuf_c_message_free_unpacked happens at the following line:
if (message->unknown_fields != NULL)
do_free(allocator, message->unknown_fields);
The do_free will free ->unknown_fields. This is may be wrong, because protobuf_c_message_unpack uses malloc as the default allocator, allocates rv with malloc. At the end, however, ->unknown_fields is only initialized if there are some. That means if there are no such fields ->unknown_fields is an uninitialized pointer.
The patch initializes the pointer to NULL to ensure the check before free is performed on initialized memory in case there is no unknown_field.
This fixes https://github.com/protobuf-c/protobuf-c/issues/690
=> Fix memory corruption by initlizalizing pointer

.github/workflows/build.yml, build-cmake/CMakeLists.txt
The CMake module is used by default but isn't compatible with recent protobuf version.
Try to first look for a protobuf config then fallback to legacy cmake module.
=> Fix CI issues with CMake

.github/workflows/build.yml
This might fix the new CI build failure:
→ Run ./autogen.sh
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4 ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /opt/homebrew/Cellar/autoconf/2.72/bin/autoconf --force
autoreconf: running: /opt/homebrew/Cellar/autoconf/2.72/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:14: installing 'build-aux/compile'
configure.ac:13: installing 'build-aux/install-sh'
configure.ac:13: installing …
=> build.yml: Install libtool on OS X

.github/workflows/build.yml
It doesn't seem that the `next` branch is getting regularly built (https://github.com/protobuf-c/protobuf-c/actions?query=branch%3Anext shows the last build was 9 months ago) so let's push some miscellaneous CI updates.
=> Miscellaneous CI updates

.github/workflows/build.yml
The default is to build on pull request activity types opened, reopened, and synchronize. Also build on activity types edited, ready_for_review, and review_requested.
=> build.yml: Build on more pull request activity types

protoc-c/c_file.cc, protoc-c/c_generator.h, protoc-c/c_helpers.h
This branch should fix several compatibility issues with the most recent Google protobuf release (26.0).
The Google protobuf `FileDescriptorLegacy::syntax()` method no longer exists in protobuf 26.0, and the `FileDescriptorLegacy` class itself is apparently deprecated and will be removed, so the `FieldSyntax()` helper in protobuf-c has been reimplemented by querying the `FileDescriptorProto` object directly. This appears to work on a wide range of Google protobuf versions at least as far back as the one shipped in Ubuntu 20.04 without any version-specific workarounds. Hopefully it continues to work.
`FileGenerator::GenerateHeader()` was also relying on `FileDescriptorLegacy::syntax()`, but we don't really need to cater to versions of protobuf-c that are now 7-10 years old, so this method …
=> Chase compatibility issues with Google protobuf >= 26.0

.github/workflows/build.yml
For MSVC:
- Updated abseil from 20230802.0 to 20240722.0.
- Updated protobuf from 24.3 to 29.3.
- Dropped utf8_range since this appears to have been incorporated into protobuf.
=> build.yml: Update Windows dependencies (abseil, protobuf)

.github/workflows/build.yml
- Add Ubuntu 22.04, 24.04 to the standard distcheck job.
- Add Ubuntu 22.04, 24.04 to the CMake job.
- Convert Valgrind job from Ubuntu 20.04 to 24.04.
- Convert coverage job from Ubuntu 20.04 to 24.04.
- Convert the run-on-arch-action job to run on Ubuntu 24.04 (base) and Ubuntu 22.04 (the arch-specific actions; Ubuntu 24.04 not available).
- Add riscv64 to the list of architectures for the run-on-arch-action job to run on.
=> build.yml: Ubuntu: Add 22.04, 24.04

build-cmake/CMakeLists.txt
If protobuf-c is already installed on the system, the cmake build can generate an error like the following when using the ninja backend:
edmonds@chase{0}:/tmp/protobuf-c$ cmake -S build-cmake -B build -G Ninja
[...]
edmonds@chase{0}:/tmp/protobuf-c$ ninja -v -C build
ninja: Entering directory `build'
[1/19] cd /tmp/protobuf-c/build && /usr/bin/cmake -E env PATH="/tmp/protobuf-c/build:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/home/edmonds/bin:/home/edmonds/.cargo/bin:/sbin:/bin:/usr/games" /usr/bin/protoc --cpp_out /tmp/protobuf-c/build -I/usr/include -I/tmp/protobuf-c /tmp/protobuf-c/protobuf-c/protobuf-c.proto
FAILED: CMakeFiles/protoc-generated-files protobuf-c/protobuf-c.pb.cc protobuf-c/protobuf-c.pb.h /tmp/protobuf-c/build/CMakeFiles/protoc-generated-files …
=> cmake: Fix build when using ninja and protobuf-c already installed

Makefile.am, protoc-gen-c/c_enum.cc, protoc-gen-c/c_enum_field.cc, protoc-gen-c/c_field.cc, protoc-gen-c/c_helpers.cc, protoc-gen-c/c_helpers.h, protoc-gen-c/c_message.cc, protoc-gen-c/c_primitive_field.cc, protoc-gen-c/c_service.cc, protoc-gen-c/compat.h
protobuf 30 (https://github.com/protocolbuffers/protobuf/releases/tag/v30.0-rc1) breaks the build of protobuf-c <= 1.5.1 due to the change of various return types away from `const std::string&` for returning string views:
> v30 will update return types in descriptor (such as full_name) to be absl::string_view.
https://protobuf.dev/news/2024-10-02/#descriptor-apis
This branch replaces various uses of `const char *` and `const std::string&` with our own `compat::StringView` typedef that handles the `const std::string&` change across the multiple versions of protobuf that protobuf-c supports.
Some extremely old code was using new/delete to allocate arrays of objects that previously were storing `const char *`'s. That code was updated to use `std::vector`.
Some internal functions that are not …
=> Chase compatibility issues with Google protobuf 30.0-rc1

protoc-gen-c/c_enum.cc, protoc-gen-c/c_field.cc, protoc-gen-c/c_helpers.cc, protoc-gen-c/c_message.cc, protoc-gen-c/c_service.cc
protobuf 30.x changes various APIs to return `string_view`'s rather than `string&`'s. This broke protobuf-c, since we were relying on the implicit construction of strings from `string&`'s in various places.
This commit explicitly constructs strings from the `string_view`'s returned by the protobuf 30.x API when we need to store an owned string (e.g. in a hash map). This maintains compatibility with older versions of protobuf such as 3.21 in Debian/Ubuntu while extending compatibility to the latest protobuf 30.x.
Without this commit we get lots of errors like this when compiling against protobuf 30.x:
protoc-gen-c/c_field.cc:119:43: error: no match for 'operator=' (operand types are 'std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >::mapped_type' {aka …
=> protoc-gen-c: Explicitly construct strings where needed for protobuf 30.x
